from __future__ import annotations

from typing import Protocol

from Instructor import Instructor
from PublicInstructorProfile import PublicInstructorProfile


class InstructorRepo(Protocol):
    def get_by_id(self, instructor_id: int) -> Instructor | None: ...
    def get_k_n_short_list(self, k: int, n: int) -> list[PublicInstructorProfile]: ...
    def add(self, item: Instructor) -> Instructor: ...
    def replace_by_id(self, instructor_id: int, new_item: Instructor) -> bool: ...
    def delete_by_id(self, instructor_id: int) -> bool: ...
    def get_count(self) -> int: ...
    def sort_by_last_name(self, reverse: bool = False) -> list[Instructor]: ...
